# Jekyll Resume Theme

# Site settings
title: Jekyll Resume
email: email@domain.com
description: Jekyll Resume is a mega simple resume theme for Jekyll.
baseurl: ""
url: "https://github.com/Crayon2/jekyll-resume.git"
name: 刘瑜鹏
job: front end engineer
location: CN
languages: HTML, CSS and Javascript
twitter_username: 
github_username:  Crayon2
codepen_username:  Crayon2
email_address: some@email.com

# Build settings
markdown: kramdown
